### ISSUE TITLE
Icon theme is broken on vs-code insiders edition

### ISSUE THREAD

**Issue by Ok9xNirab** [BeardedBear/bearded-icons#10]
Hi ,
I'm using vs-code insiders (ARMx64) edition .

<img src="https://i.ibb.co/DRHNmCP/Screenshot-2021-01-28-at-4-42-45-AM.png" />

**In my windows desktop , it's works fine**

Thanks.

**Comment by BeardedBear** [comment]
Thank you for warning! I fixed it in version 0.9.1! For a reason I don't know, there is a regression in the interpretation of SVG files :(
