### ISSUE TITLE
.jsx File Extension Not Showing

### ISSUE THREAD

**Issue by maxx-em** [BeardedBear/bearded-icons#108]
Not sure if this is a bug or if there is something I'm missing but a JSX file shows the default JS icon.
![image](https://user-images.githubusercontent.com/93453124/220200916-249e59b9-200d-4dbf-9d25-7e85ec51b487.png)

**Comment by BeardedBear** [comment]
It's strange, I don't have this problem at all on my side...
![image](https://user-images.githubusercontent.com/7188702/220202088-914d086b-91df-4fc8-99ba-4eb188283fd6.png)
Can you tell me what version of the extension and VSCode you have installed? Or maybe your OS?

**Comment by maxx-em** [comment]
I have the latest version of the extension (1.4.0) and the latest version of VSCode. I have the latest version of Windows 10 too.

**Comment by maxx-em** [comment]
I've fixed the issue, my VSCode language mode was set to Javascript instead of Javascript JSX.

**Comment by BeardedBear** [comment]
Okay, great ! Thanks !
