### ISSUE TITLE
Create .mustache icon?

### ISSUE THREAD

**Issue by dBianchii** [BeardedBear/bearded-icons#125]
![image](https://user-images.githubusercontent.com/17372417/230233607-3fc03b03-0466-42be-aaf3-f9ebbaac50bf.png)

Would be good to have .mustache icons

**Comment by BeardedBear** [comment]
Done :)

**Comment by dBianchii** [comment]
Just wanted to share that this is the first issue I open in an open source repo that gets completed. (and so quick too 😊)

Feeling happy because I love BeardedIcons ❤️

**Comment by BeardedBear** [comment]
Welcome to the open source world ! :D
