### ISSUE TITLE
.jsx extention doesn't work

### ISSUE THREAD

**Issue by Tarmiel** [BeardedBear/bearded-icons#126]
.js icon is displayed for .jsx files. 

![Screenshot_1](https://user-images.githubusercontent.com/91093431/230649591-5f1dd3f4-5539-4065-b230-93b01c224c47.jpg)

I'm not sure what the actual problem is (maybe it's just me who has this problem), but I was able to fix it by adding 
`"jsx": "_f_reactjs"` to `fileExtensions` in `icons.json` file

extension version: 1.10.0
vscode version: 1.77.0

**Comment by BeardedBear** [comment]
My bad ! I upload the fix today :)
