### ISSUE TITLE
Icon request: Drizzle ORM

### ISSUE THREAD

**Issue by ColinEspinas** [BeardedBear/bearded-icons#137]
Hey, hope you are doing well.

Would be great to add an icon for drizzle config files.

From the [docs](https://orm.drizzle.team/kit-docs/conf), the possible file syntax for those files are:
- drizzle.config.ts
- drizzle.config.js
- drizzle.config.json

Have a great day,
Colin.

**Comment by BeardedBear** [comment]
Thanks ! Done in v1.13.0 !
