### ISSUE TITLE
.bicepparam should be file extension

### ISSUE THREAD

**Issue by nahlian** [BeardedBear/bearded-icons#138]
Thank you for the recent icon for .bicepparam, love the orange.  Currently, the icon only works when the file is named .bicepparam. I think this because the .bicepparam is marked as file name and not file extension.  There is typically more than one .bicepparam per directory.  Below is straight from Microsoft's documentation. 

_Bicep parameters file has the file extension of .bicepparam._

_To deploy to different environments, you create more than one parameters file. When you name the parameters files, identify their use such as development and production. For example, use main.dev.bicepparam and main.prod.bicepparam to deploy resources._

**Comment by BeardedBear** [comment]
Oops ! My bad, it's fixed in v1.13.2 !
