### ISSUE TITLE
Icon request: .proto

### ISSUE THREAD

**Issue by gustavobarca** [BeardedBear/bearded-icons#139]
Hi! It would be nice to have the icon for gRPC definition files (.proto).

**Comment by FelixKLG** [comment]
Does Protobuf have a logo? After some Googling it looks like they just wrap the word protobuf inside of the Google developer logo? Or they use some ugly floppy disk logo.

**Comment by gustavobarca** [comment]
No, i don't think so. Using material-icons as benchmark, you are correct, i think the most ideal icon would be the Google Developer Logo:

**Material icon protobuf:**

![image](https://github.com/BeardedBear/bearded-icons/assets/40965435/1051022d-0912-4ab5-ac55-1863d8f19def)


**Google developer logo:**

![image](https://github.com/BeardedBear/bearded-icons/assets/40965435/f669540f-6c4b-4773-aa94-df2f06b8b512)
