### ISSUE TITLE
Icon request Excalidraw

### ISSUE THREAD

**Issue by eye-wave** [BeardedBear/bearded-icons#143]
Excalidraw editor is available in VScode via extension.
its sketches are saved in `.excalidraw`, `.excalidraw.json`, `.excalidraw.svg` or `.excalidraw.png`

**Comment by dBianchii** [comment]
OOhh, I was about to suggest this. Went into this repo just to request this! <3

+1 For me please!

![image](https://github.com/BeardedBear/bearded-icons/assets/17372417/3cdf3aa1-c3d1-4b7d-95ac-d354c69dd031)

**Comment by BeardedBear** [comment]
Hi there! The version (1.14.0) including the request is available!
