### ISSUE TITLE
Docker icon not showing if docker-compose file name is custom

### ISSUE THREAD

**Issue by haziqfiqri** [BeardedBear/bearded-icons#144]
It's not really an urgent issue, but it really give me the OCD. I appreciate that custom docker or docker-compose file name show the actual icon instead. Thanks!

**Screenshot:**

![Screenshot 2023-08-28 152942](https://github.com/BeardedBear/bearded-icons/assets/29334629/54c4b8ef-ca4c-4603-80cc-66a0cbff0e3f)

**Comment by BeardedBear** [comment]
Salut ! Ce que vous souhaitez ne semble pas possible à ma connaissance, la seule astuce que je peux vous donner (et que j'ai mis en place dans la PR) c'est de creer un ficher qui se termine pas `.docker-compose.yml`, exemple : `custom-name.docker-compose.yml`

**Comment by haziqw** [comment]
> What you're asking doesn't seem possible.
> 
> The only tip I can give you (and which I've implemented in the PR) is to create a file that ends with `.docker-compose.yml`, for example: `custom-name.docker-compose.yml`.

Thanks bear! This would do.

**Comment by BeardedBear** [comment]
Hi there! The version (1.14.0) including the request is available!

**Comment by notmedia** [comment]
@BeardedBear Hey, could you add the rule for `.docker-compose.yaml`? Right now supported only `.yml` format
