### ISSUE TITLE
feature request: change folder colore + add stylellintrc.js/cjs  file  icon  

### ISSUE THREAD

**Issue by issam-seghir** [BeardedBear/bearded-icons#148]
I wish I could change the folder icon to a darker color. Perhaps you could consider adding a feature to customize folder colors and showing arrows   in the settings , 
Also, it would be great if you could include an icon for Stylelint config files.

![image](https://github.com/BeardedBear/bearded-icons/assets/74573675/a47d9d0a-0876-4aea-a06e-c23b995d2044)

- darker color icons like this : 
![image](https://github.com/BeardedBear/bearded-icons/assets/74573675/2d0ab76b-648b-421a-961b-71ec809ac708)

**Comment by BeardedBear** [comment]
Hi! The stylelint file will be fixed in the next release! Thanks for the suggestion, but I prefer the files lighter as they are! (having said that, in a previous PR, I slightly tinted the folders to make it look a bit better, that's something!)

**Comment by BeardedBear** [comment]
Hi there! The version (1.14.0) including the request is available!
