### ISSUE TITLE
Support for lapce editor

### ISSUE THREAD

**Issue by zero-pytagoras** [BeardedBear/bearded-icons#170]
Hello,
I am wondering if it will be possible to port the plugin for the [lapce editor](https://lapce.dev/) ?

**Comment by Redhawk18** [comment]
> Hello, I am wondering if it will be possible to port the plugin for the [lapce editor](https://lapce.dev/) ?

I've actually emailed the author about releasing a `TTF` file to let us parse through the font to display the icons. They haven't got back to me yet...

[But I did create a script to parse a font file to generate rust code](https://github.com/Redhawk18/mamba-bronze).

**Comment by Redhawk18** [comment]
looking into it, a lot of icons made it before the license change, so you could use anything in the repo at this commit, since it's MIT.

https://github.com/BeardedBear/bearded-icons/tree/f2da5a1f3db62c8901528240ec0140e4d973776b

**Comment by BeardedBear** [comment]
Hi there!

@zero-pytagoras: I'm not planning to create a port for Lapce at the moment, it's not a sufficiently mature editor at the moment (pre-alpha) to take the time to port it, I reinstalled it recently to monitor progress, and the syntax colorization is too buggy at the moment, and I don't like it visually. (I'll watch the project, and think about it again when it's more advanced). I'm the only one maintaining/creating my extensions, I prefer to concentrate on more common editors, like the Jetbrain suite for example.

@Redhawk18: I received your email, I was going to reply tomorrow, I have a lot of work at the moment. It all depends on what you intend to do with my icon pack, if you intend to make money with it, I'm against it. If it's for personal use only, I don't mind.

**Comment by Redhawk18** [comment]
> Hi there!
> 
> @zero-pytagoras: I'm not planning to create a port for Lapce at the moment, it's not a sufficiently mature editor at the moment (pre-alpha) to take the time to port it, I reinstalled it recently to monitor progress, and the syntax colorization is too buggy at the moment, and I don't like it visually. (I'll watch the project, and think about it again when it's more advanced). I'm the only one maintaining/creating my extensions, I prefer to concentrate on more common editors, like the Jetbrain suite for example.
> 
> @Redhawk18: I received your email, I was going to reply tomorrow, I have a lot of work at the moment. It all depends on what you intend to do with my icon pack, if you intend to make money with it, I'm against it. If it's for personal use only, I don't mind.

Thank you for responding. I want to use your icon pack as the default icons in [my IDE](https://github.com/Redhawk18/blaze), its even further be hide lapace but it's only me. I don't plan on ever charging for anything in this project, and all I ask for is a TTF file. I can parse it and handle adding it to my project. I don't actually know much about how vector graphics and fonts work at a low level.

**Comment by Redhawk18** [comment]
Now I figured out fonts are hard, and it puts me in a pickle because my project uses the MPL and this project uses the GPL.

**Comment by BeardedBear** [comment]
I understand your frustration, but I don't want to create a font with my pack, I have no use for it. Having said that, you can try using Material Icons, the icons aren't that different from mine, and are MIT licensed :) https://github.com/PKief/vscode-material-icon-theme
