### ISSUE TITLE
Icon for Prolog files (.pl)

### ISSUE THREAD

**Issue by D4C4N** [BeardedBear/bearded-icons#189]
Hello, 

I wanted to propose the inclusion of an icon for `.pl`-files for Prolog. Currently, it defaults to the Perl-icon, even if the file type is set to be for Prolog. 

As for an idea, I could imagine a stripped down version of the Prolog-logo:

![image](https://github.com/BeardedBear/bearded-icons/assets/82240359/0a6eaa6e-506e-477e-a611-9bbdc434425b)

Thank you :)

**Comment by BeardedBear** [comment]
hi! i've already created an icon for prolog, but i haven't added it for .pl files, it will be fixed in the next version ;)

**Comment by D4C4N** [comment]
> Hi! I've already created an icon for prolog (for .pro files), but for the .pl extension, I've already got the Pearl assigned, so I'm a bit annoyed haha.

Ahhh, I see. Yeah if you had to choose between the two of them, perl is most likely more important.
