### ISSUE TITLE
Missed icon for .tsx extension

### ISSUE THREAD

**Issue by abakimatov** [BeardedBear/bearded-icons#2]
Hello! Great icons theme, but unfortunately icon for `.tsx` extension is missed. Can you add it?

![image](https://user-images.githubusercontent.com/30955537/93014252-447c3600-f5b8-11ea-858f-a00ed4bd4c64.png)

**Comment by abakimatov** [comment]
also wil be great if you add icons for erlang and elixir files icons. :)

**Comment by BeardedBear** [comment]
Thank you! I'll do that as soon as possible :)

**Comment by BeardedBear** [comment]
Done !

**Comment by abakimatov** [comment]
> Done !

Thank you!:)
