### ISSUE TITLE
Storybook Icon (*.stories.*)

### ISSUE THREAD

**Issue by gabrielalg** [BeardedBear/bearded-icons#22]
Hi! It would be nice to have a custom icon for files with ` .stories` extension. 

![image](https://user-images.githubusercontent.com/50120237/125336809-9f8bd000-e324-11eb-8357-4cdfd158bd85.png)

I have see some examples in another icon packages, like this:
![image](https://user-images.githubusercontent.com/50120237/125337011-d661e600-e324-11eb-9bdd-dd0dffe9a171.png)

Thank you in advance! By the way, great work with this package, I really like it! :grinning:

**Comment by BeardedBear** [comment]
Done in version 0.12.0 ! :)

**Comment by gabrielalg** [comment]
Thank you! 🙌😃
