### ISSUE TITLE
Folders icons

### ISSUE THREAD

**Issue by davidhdez** [BeardedBear/bearded-icons#29]
Aloha, I like the design of your themes for VS Code.
I wondered if you had thought about add folder icons to it. 
Style inspired in the icons of Material Theme. Thank you.

**Comment by BeardedBear** [comment]
Hi! No, i don't plan to add icons to the folders, except for some very particular ones, it's an option I don't like it in the icon packs, I have the feeling that it doesn't bring much and that it loses readability :)
