### ISSUE TITLE
Missing icons for postcss

### ISSUE THREAD

**Issue by oktay** [BeardedBear/bearded-icons#3]
Hello, there is no icons for css files associated as postcss

![image](https://user-images.githubusercontent.com/3390175/94322249-98185780-ff9a-11ea-9493-cbccc51973b5.png)
![image](https://user-images.githubusercontent.com/3390175/94322264-a1092900-ff9a-11ea-8bc3-13137be14285.png)

**Comment by BeardedBear** [comment]
Done ! Thanks ! :D
