### ISSUE TITLE
Navigation arrows

### ISSUE THREAD

**Issue by Almsrr** [BeardedBear/bearded-icons#31]
The design of your icons is great, but why the navigation arrows are hidden in folders? When the project has many folders, it is difficult to identify the file tree.

<img width="257" alt="file-tree" src="https://user-images.githubusercontent.com/54919831/130280050-974f5141-5afd-4e9d-819f-e878256456b8.png">

Personally, I like it better. I'll tell you if you want to implement it (I'm using your theme also).

**Comment by BeardedBear** [comment]
Because i like it simple, and i've set the setting : `editor.tabSize` to `20` ^^

![image](https://user-images.githubusercontent.com/7188702/130280555-759a7469-136c-4a4e-be99-d9c593365f51.png)

**Comment by Almsrr** [comment]
Oh, good choise, I'll try... Thanks
