### ISSUE TITLE
👩‍🔬 Icon for csv files is missing

### ISSUE THREAD

**Issue by asmaamirkhan** [BeardedBear/bearded-icons#53]
Hi 🙋‍♀️,

I noticed that icon of `.csv` files is missing.

![image](https://user-images.githubusercontent.com/45575570/141673301-ac423769-5d06-4f62-b671-8d31b6e197d5.png)

> 📝 Used theme: Bearded Theme Earth 🚀

**Comment by BeardedBear** [comment]
Hey thanks ! 

I had an issue about this, I fixed it, it will be available in the next version (today or in the next days) : https://github.com/BeardedBear/bearded-icons/issues/25

**Comment by asmaamirkhan** [comment]
Great! 🎉
Waiting for it 🚀
