### ISSUE TITLE
Support root folder icon

### ISSUE THREAD

**Issue by mikenavi** [BeardedBear/bearded-icons#75]
Is it possible to add root folder icon (or maybe optional one).

**Comment by BeardedBear** [comment]
do you mean the little arrow in front of the folder icons?

**Comment by mikenavi** [comment]
Hi. I mean icon for root element in multi-root workspaces.
![image](https://user-images.githubusercontent.com/4928270/185364993-06475757-ae4b-40d0-a106-fd820fc3680d.png)

**Comment by BeardedBear** [comment]
Okay ! its ready for next release for today :)

**Comment by mikenavi** [comment]
Wow, great! Thank you
