### ISSUE TITLE
Add Nix icons

### ISSUE THREAD

**Issue by tedbyron** [BeardedBear/bearded-icons#78]
[Nix](https://nixos.org/) language and package manager use files that end in `.nix`. There are also [Nix flakes](https://nixos.wiki/wiki/Flakes) that are similar to package.json/package.lock and use a flake.nix file with `flake.lock` lock file

**Comment by BeardedBear** [comment]
Done! It will be available in a few minutes, while the package is well deployed on Microsoft servers ^^

**Comment by tedbyron** [comment]
looks great!
