### ISSUE TITLE
[Request] Cypress Config File Icon

### ISSUE THREAD

**Issue by burakkaygusuz** [BeardedBear/bearded-icons#79]
The config [icon ](https://media-exp1.licdn.com/dms/image/C4D0BAQGt-oTqjc4gOA/company-logo_200_200/0/1649346796554?e=1669248000&v=beta&t=-N53D_MRa-zIB6yzCkg36BbNXyOeLYl-bI12tcXq39U)is missing for **cypress.config.js**. This configs belongs to [cypress](https://www.cypress.io) test framework. Could you please add it? Thanks.

**Comment by BeardedBear** [comment]
Done :)
