### ISSUE TITLE
Missing icons for nginx.conf and .env files

### ISSUE THREAD

**Issue by threes-was-taken** [BeardedBear/bearded-icons#8]
[Edit] : (forgot to add description 😅 )

Please add icons for .env and nginx.conf files.
All other icons are very very nice, thank you very much!

**Comment by alsanchez-dev** [comment]
Either there is icon for .sql 😞

**Comment by BeardedBear** [comment]
Hi ! Thanks for your feedback, done in 0.7.0 !
