### ISSUE TITLE
The icons for .edge files are no longer the same.

### ISSUE THREAD

**Issue by JeanDevFR** [BeardedBear/bearded-icons#85]
Hello,

Since update 0.26.0, icons for .edge files (AdonisJS) are not correct.

Have a nice day.

**Comment by BeardedBear** [comment]
hello,

I modified it after discovering that there seems to be an official Edge Template logo : https://github.com/edge-js :)

**Comment by JeanDevFR** [comment]
> hello,
> 
> I modified it after discovering that there seems to be an official Edge Template logo : https://github.com/edge-js :)

I use it almost everyday and didn't even notice it. I was used to the previous icons.

I am really sorry.
