### ISSUE TITLE
The readme icon is kinda hard to see at a small size

### ISSUE THREAD

**Issue by lucasrmendonca** [BeardedBear/bearded-icons#90]
![readme-icon](https://user-images.githubusercontent.com/5521917/194183275-8983b62f-1005-4787-8f41-225a3ccf85cd.png)

IMO the readme icon is too detailed compared to the other icons, which makes it hard to identify as a "book" when it's in small size... also it has a very bright color, which makes it stand out too much from the dark background when compared to other icons.
 
What do you think of a readme icon that's less detailed such as the Github Wiki icon? Also, an open book kinda conveys the "Read me" concept better than a closed one, don't you think?

![Wiki](https://user-images.githubusercontent.com/5521917/194184097-a550ea12-b9c5-420e-8ff7-18dcea18c6c4.png)

**Comment by BeardedBear** [comment]
Thanks, done !
